TOKEN = "8637734040:AAEOJA4vQ1-Da2abanKOCVuR5ArTNESJhnc"

# Состояния
AUTH_LOGIN, AUTH_PASSWORD = range(2)
REG_ROLE, REG_FULL_NAME, REG_USERNAME, REG_PASSWORD, REG_CLASS, REG_SUBJECT, REG_CHILD = range(7)
BROADCAST_TEXT = 0
TEACHER_ENTER_GRADE, TEACHER_ENTER_COMMENT, TEACHER_ENTER_HOMEWORK, TEACHER_BROADCAST_TEXT = range(4)
PARENT_MESSAGE_TO_TEACHER = 100